#!/bin/bash
#
# bashprompt
#
# if there is an xterm open at a bash prompt, raise/focus that window
# if there isn't start a new xterm
#
# Assumes that your xterm window title includes your short hostname.
# If it doesn't, you should change the prompttitle variable below.
#
# see <http://unix.stackexchange.com/questions/6842> for more details
# and an example .bashrc to set the title (requires bash 3.2 or newer)
#
# Mikel Ward <mikel@mikelward.com>

debug=false
$debug && exec >>$HOME/bashprompt.log 2>&1

# change this to whatever is unique about your window title
# (i.e. a string that appears in the title when the shell is at a prompt
#  but does not appear when running a command)
prompttitle="$(hostname -s)"
terminalprog=("gnome-terminal" "--tab" "--maximize")

if ! type wmctrl >/dev/null 2>&1; then
    echo "wmctrl can't be found, please install it" 1>&2
    exit 1
fi

if ! output="$(wmctrl -l)"; then
    echo "Error running wmctrl -l" 1>&2
    exit 1
fi
while read -r id desktop host title; do
    if [[ $title =~ $prompttitle ]]; then
        $debug && echo "$title matches $prompttitle" 1>&2
        break
    fi
done <<EOF
$output
EOF

if test -n "$id"; then
    $debug && echo "Focusing $id" 1>&2
    wmctrl -i -a "$id"
else
    $debug && echo "Running ${terminalprog[*]}" 1>&2
    "${terminalprog[@]}"&
fi
