#!/bin/bash

# Works with $EDITOR to use vscode as editor if run from inside vscode.

case "$TERM_PROGRAM" in
vscode)
    ;;
*)
    # Pretend this script isn't available.
    exit 127;;
esac

# Switch <filename> +<lineno> to --goto <filename>:<lineno>
declare -a args
args=("$@")
for ((i=0; i<${#args[@]}; i++)); do
    arg="${args[i]}"
    case "$arg" in +*)
        file="${args[i-1]}"
        line="${arg#+}"
        args[i-1]="--goto"
        args[i]="${file}:${line}"
        ;;
    *)
        ;;
    esac
done

# Antigravity sets TERM_PROGRAM=vscode and ANTIGRAVITY_CLI_ALIAS=antigravity.
# We could try looking at the parent process name and only calling
# $ANTIGRAVITY_CLI_ALIAS if we were run inside Antigravity, but this seems
# simpler and good enough for now.
${ANTIGRAVITY_CLI_ALIAS:-code} --wait "${args[@]}"
