#!/bin/sh
# Create tarballs of configuration directories.

trap "exit" INT TERM QUIT

# One tarball per ~/conf.* directory.
cd
for dir in conf/ conf.*/; do
  test -d "$dir" || continue

  tarball="${dir%/}.tar.gz"
  echo "Backing up $dir to $tarball"

  cd "$dir"
  find . '(' -name '.*' ')' -prune -o '(' -type f -o -type l ')' -print0 |
  pax -w -z -L -0 -f "$HOME/$tarball"
  cd "$OLDPWD"
done
