#!/bin/sh
# $Id: confback,v 1.5 2005/07/09 14:54:58 michael Exp $
# Create tarballs of configuration directories.

# One tarball per ~/conf.* directory.
cd
for dir in conf/ conf.*/; do
  test -d "$dir" || continue

  tarball="${dir%/}.tar.gz"
  echo "Backing up $dir to $tarball"

  cd "$dir"
  find . '(' -name '.svn' -o -name '.git' ')' -prune -o '(' -type f -o -type l ')' -print0 |
  pax -w -z -L -0 -f "$HOME/$tarball"
  cd "$OLDPWD"
done
