#!/usr/bin/env perl
# print file systems over a certain percentage full

use warnings;

use Getopt::Long;

my $threshold = 95;	# report file systems over this percent used
my $help;

GetOptions ("help|h" => \$help,
            "threshold|t:s" => \$threshold)
            or usage();
if ($help) { usage(); }

# symbols for multiples of 1024 bytes
my @suffixes = ("KB", "MB", "GB", "TB", "PB", "EB");

# output format for file systems at or above threshold
format STDOUT = 
@<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< @>>>> @<
$mount,                                 $free,$suffixes[$power]
.

my $full = 0;	# number of file systems at or above threshold

@output = `df -Pk`;	# retrieve disk space information
shift @output;	# strip header
foreach my $line (@output)
{
    $\ = "\n";
    $, = "\t";
    our ($fs, $blocks, $used, $avail, $percent, $mount) = split (/\s+/, $line);
    $percent =~ s/%$//;	# strip percent sign
    $free = $avail;
    $power = 0;
    while ($free >= 1000)	# convert to three figures plus binary suffix
    {
        $free /= 1024;
        $power++;
    }
    $free = int ($free + 0.5);	# round the displayed size to a whole number
    if ($percent >= $threshold)
    {
        $full++;
        write;
    }
}
exit $full;

# print a usage message
sub usage
{
    print "
Usage:
    diskspace [options]

Options:
    -h                 Print a message describing how to run this program
    -t percent         Show file systems that are at least percent full
";
    exit 2;
}

# vi: set sw=4 ts=33:
