#!/bin/bash
# edit a file, with sudo if current user lacks write permissions
# also turns file:line into file +line

set -e
set -u

SUDO=sudo                    # empty is false, non-empty is true
EDITOR=${EDITOR:-vi}

error() {
    printf "$*\n"
    false
}

try_edit_as_root() {
    printf "You don't have permission to edit %s\n" "$1"
    confirm "Edit as root" && "$SUDO" "$EDITOR" "$1"
}

if test $# -eq 0; then
    "$EDITOR"
else
    line=${1##*:}
    if test "$line" != "$1"; then
      file=${1%:$line}
    else
      line=
    fi

    set -- "$file" ${line:++$line}

    if test -e "$file"; then
        if test -w "$file"; then
            "$EDITOR" "$@"
        else
           try_edit_as_root "$@" || view "$@"
        fi
    else
        if test -w "$(dirname "$file")"; then
            "$EDITOR" "$@"
        else
            try_edit_as_root "$@" || error "$file does not exist"
        fi
    fi
fi
