#!/bin/bash
declare -a args
for arg in "$@"; do
    num="${arg##*:}"
    case "$num" in
    ''|*[!0-9]*)
        # no numeric :line suffix (the whole arg when there is no colon)
        args+=("$(realpath "$arg")")
        ;;
    *)
        if test "$num" = "$arg"; then
            # no colon at all
            args+=("$(realpath "$arg")")
        else
            args+=("$(realpath "${arg%:*}")" "+$num")
        fi
        ;;
    esac
done
declare -a editors=(
    codeedit vim
)
for editor in "${editors[@]}"; do
    type "$editor" >/dev/null 2>&1 || continue
    # exit status is 127 if a command is not found
    # codeedit returns 127 if it wants to be skipped
    "$editor" "${args[@]}"
    status=$?
    test $status -ne 127 && exit $status
done
printf '%s %s\n' "Couldn't find any editor, looked for" "${editors[*]}" >&2
exit 1
