#!/bin/bash
declare -a args
for arg in "$@"; do
    file="${arg%:[0-9]*}"
    file="$(realpath "$file")"
    args+=("$file")
    case "$arg" in *:*)
        num="${arg##*:}"
        args+=("+$num")
        ;;
    esac
done
for editor in codeedit nvimr nvim vim; do
    # exit status is 127 if a command is not found
    # codeedit returns 127 if it wants to be skipped
    "$editor" ${editor_args[$editor]} "${args[@]}"
    status=$?
    test $status -ne 127 && exit $status
done
