#!/bin/bash
monitors=$(xrandr | awk '$2 ~ /(dis)?connected/')
internal_display='eDP-1'
internal_display_connected() {
  <<<"$monitors" grep -q "^$internal_display connected"
}
external_display_connected() {
   <<<"$monitors" grep -v "^$internal_display " |
     grep -q -w 'connected'
}
disable_internal_display() {
    xrandr --output "$internal_display" --off
  }
if internal_display_connected && external_display_connected; then
    disable_internal_display
fi
