#!/bin/bash

set -e
set -u

declare -a connected_displays=( $(xrandr | awk '$2 == "connected" { print $1 }') )

is_internal() {
    case $1 in eDP-*)
        true;;
    *)
        false;;
    esac
}

is_external() {
    ! is_internal $1
}

any() {
    declare -n list=$1
    declare predicate=$2
    for x in "${list[@]}"; do
        if $predicate $x; then
            return 0
        fi
    done
    return 1
}

each() {
    declare -n list=$1
    declare func=$2
    for x in "${list[@]}"; do
        $func $x
    done
}

filter() {
    declare -n list=$1
    declare predicate=$2
    for x in "${list[@]}"; do
        if $predicate "$x"; then
            echo "$x"
        fi
    done
}

external_display_connected() {
    any connected_displays is_external
}

disable_display() {
    xrandr --output "$1" --off
}

enable_display() {
    xrandr --output "$1" --auto
}

enable_all_external_displays() {
    declare -a external_displays=( $(filter connected_displays is_external) )
    each external_displays enable_display
}

disable_all_internal_displays() {
    declare -a internal_displays=( $(filter connected_displays is_internal) )
    each internal_displays disable_display
}

if external_display_connected; then
    enable_all_external_displays
    disable_all_internal_displays
fi
