#!/bin/bash
# Send matching lines to be processed, pass non-matching lines thru unprocessed.
# Example: </etc/fstab filter "^[^#]" column -t

if test $# -lt 2; then
    printf "Usage: filter <pattern> <command> [<command args>]\n" >&2
    exit 2
fi

# Decorate, sort, then undecorate lines to ensure line order is preserved, even
# if the command uses different buffering (e.g. only produces output after
# reading all input).
# Undecorate by removing the tab separator when it survived (preserving the
# line's own leading whitespace), falling back to removing any whitespace so we
# can use "column" as the command (column converts the tab separator into
# spaces).
pattern=$1
shift
i=0
{
while IFS= read -r line || test -n "$line"; do
    i=$((i+1))
    if [[ "$line" =~ $pattern ]]; then
        printf "%d\t%s\n" "$i" "$line" >&3
    else
        printf "%d\t%s\n" "$i" "$line"
    fi
done 3> >("$@")
} |
sort -k1n |
sed -e 's/^[0-9][0-9]*	//' -e t -e 's/^[0-9][0-9]*[[:space:]]*//'
