#!/bin/bash
url="$1"
git clone "$url" || exit 1
dir=${url##*/}
dir=${dir%.git}
# Guard the cd: rewriting remotes in whatever repository encloses the current
# directory would be destructive.
cd "$dir" || exit 1
git remote add upstream "$url"
case "$url" in
"git@github.com:"*)
    echo "Please fork the repository on GitHub at $url"
    ;;
*)
    echo "Please create the $dir repository on GitHub at https://github.com/new"
    ;;
esac
echo "Press ENTER when done"
read
git remote remove origin
git remote add origin "git@github.com:mikelward/$dir"
git push origin
