#!/bin/sh

# Close stdout and stderr so it doesn't keep the terminal open.
exec >/dev/null 2>/dev/null

username=$(whoami)
short_hostname=$(hostname)
short_hostname=${short_hostname#$username-}
short_hostname=${short_hostname%%.*}
i3status | while read -r line; do
    line="$(echo "$short_hostname $(showconn) $line" |
        sed -e 's#/ DisplayPort ##' \
            -e 's/Headset/🎧/g' \
            -e 's/Speaker/🔉/g'
            -e 's/|//g' \
            -e 's/  */ /g')"
    xsetroot -name "$line"
done
