#!/bin/sh
i3status -c "$HOME/.config/i3status/dwm" | while read -r line; do
    line="$(echo "$line" | sed -e 's#/ DisplayPort ##')"
    line="$(echo "$line" | tr -s ' ')"
    xsetroot -name "$line"
done
