#!/usr/bin/env perl
# send mail to the specified address if standard input contains lines of input
# $Id$

if (@ARGV < 1)
{
    print STDERR "Usage: mailifnotempty <address> [<subject>]\n";
    exit 2;
}

my $address = shift @ARGV;
my $subject = shift @ARGV;

if (!eof(STDIN))
{

    # list form so quotes/$/backticks in the subject or address can't be
    # interpreted by a shell
    my @command = ('/usr/bin/mail');
    push @command, '-s', $subject if defined($subject);
    push @command, $address;
    open(PIPE, '|-', @command)
        or die "Cannot invoke @command";

    while ($line = <STDIN>)
    {
        print PIPE $line;
    }

    close PIPE;
}

