test:
	./autoshpool_test
	./autotmux_test
	./autosession_test
	./sessionlib_test
	./changeshpool_test
	./changetmux_test
	./changesession_test
	./detachsession_test
	./makesession_test
	./mdf_test
	./pa_test
	./package_test
	./homepkg_test
	./gittossh_test
	./gitbackup_test
	./runenv_test
	./setup_test
	./setup-hypr_test
	./setup-sway_test
	./setup-kde_test
