test:
	./autoshpool_test
	./autotmux_test
	./autosession_test
	./sessionlib_test
	./changeshpool_test
	./changetmux_test
	./changesession_test
	./detachsession_test
	./makesession_test
	./mdf_test
	./pa_test
	./package_test
	./homepkg_test
	./gittossh_test
	./gitbackup_test
	./runenv_test
	./setup_test
	./setup-kde_test
	./setup-macos_test
	./kdeshortcut_test
	./dvorak_test
	./confinst_test
	./repo-rules_test
	./repo-rules-audit_test
