#!/bin/sh

dir=$1

error()
{
	echo "$*" 1>&2
}

usage()
{
	echo "Usage: makexpi [<directory>]" 1>&2
}

if test -z "$dir"; then
	dir=.
fi

rdf="$dir/install.rdf"
if test ! -f "$rdf"; then
	error "Cannot find $rdf"
	exit 1
fi

# XXX should part the XML but Dreamhost doesn't have XMLStarlet etc.
version=$(sed -ne '/<em:version>/ s/.*<em:version>\(.*\)<\/em:version>.*/\1/p' "$rdf")
name=$(sed -ne '/<em:name>/ s/.*<em:name>\(.*\)<\/em:name>.*/\1/p' "$rdf")

#echo "$name $version"
xpi=$(echo "$name $version".xpi | sed -e 's/\([A-Z]\)/\l\1/g; s/ /-/g')
echo "Creating $xpi"
prunesvn "$dir" \( -name "content" -prune \) -o \( -name "locale" -prune \) -o | zip -@ "$xpi"
