#!/bin/bash
# Create a Visual Studio Code task runner for the current project, based
# on the presence of a build system configuration file.
# For example, if the current directory has a BUILD file, maketasks will copy
# ~/templates/tasks.json.BUILD to .vscode/tasks.json.

cd "$1" || exit
test -d .vscode || mkdir .vscode
test -f .vscode/tasks.json && exit 0

for f in "$HOME/.templates/tasks.json."*; do
  test -f "$f" || break  # no templates => f == tasks.json.*
  if test -f "${f#$HOME/.templates/tasks.json.}"; then
    cp "$f" .vscode/tasks.json
    exit 0
  fi
done
