test:
	./autoshpool_test
	./autotmux_test
	./autosession_test
	./sessionlib_test
	./changeshpool_test
	./changetmux_test
	./changesession_test
	./detachsession_test
	./makesession_test
	./mdf_test
	./setup_test
	./setup-hypr_test
	./setup-sway_test
	./setup-kde_test
	./kde-recover_test
