#!/bin/bash

if xrandr | grep -q "^DP-1 connected "; then
  xrandr --output DP-1 --auto && xrandr --output eDP-1 --off
else
  xrandr --output eDP-1 --auto
fi

#xrandr --output DP-1 --auto --right-of eDP-1
#current_workspace=$(
#i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name'
#)
#for workspace in $(
#i3-msg -t get_workspaces | jq -r '.[1:][].name'
#); do
#    i3-msg workspace $workspace
#    i3-msg move workspace to output DP-1
#done
#i3-msg workspace $current_workspace
