#!/bin/bash
#
# print information about each song as it starts playing
#
# Rhythmbox only at the moment
#

interface=org.gnome.Rhythmbox.Player
member=playingUriChanged

dbus-monitor --profile "interface='$interface',member='$member'" |
while read -r line; do
    printf "Now playing: "
    rhythmbox-client --print-playing
done

