#!/bin/bash
# print information about a single option or command
# Mikel Ward <mikel@mikelward.com>

# Example Usage:
# opt bash continue
# opt rsync -v

if test $# -ne 2; then
    echo "Usage: opt <command> <option>" 1>&2
    exit 2
fi

# TODO handle -s <section> etc.
manpage="$1"
option="$2"

# XXX man calls col when it's part of a pipeline,
# which strips the bold and underline, and breaks
# UTF-8 encoding (try "man bash" for example)
# set LANG=C until a better solution is found
LANG=C man "$manpage" | perl -n -e "
BEGIN {
    \$option = \"$option\";
    \$inside = 0;
}"'
if (!$inside) {
    if (/^(\s*)\Q$option\E\b/p) {
        # start of this option
        $spaces = $1;
        $inside = 1;
        print;
    }
}
else {
    if (/^$spaces\S/) {
        # start of next option;
        exit;
    }
    elsif (/^\S/) {
        # start of next section
        exit;
    }
    else {
        print;
    }
}
' | "${PAGER:-less}"
