#!/bin/bash
# precommit hook for git, hg, etc.
set -e

source ~/.shrc.vcs

allknown

rootdir="$PWD"
while IFS=$'\n' read path; do
    cd "$rootdir"
    cd "$(dirname "$path")"
    while test "$PWD" != "/"; do
      test -f .Makefile && break
      cd ..
    done
done <<<"$(changed)"
make -f .Makefile test
