#!/bin/bash
xset s 300 5

if test -x "$(command -v mate-screensaver)"; then
  case $1 in
    init)
      (setsid mate-screensaver&)
      ;;
    lock)
      exec mate-screensaver-command --lock
      ;;
    esac
elif false; then
#if test -x "$(command -v xsecurelock)"; then
  if test -f "$HOME/.xsecurelockrc"; then
      . "$HOME/.xsecurelockrc"
  fi
  case $1 in
    init)
      (xss-lock -l -- xsecurelock&)
      ;;
    lock)
      exec xsecurelock
      ;;
  esac
else
  case $1 in
    init)
      (setsid xscreensaver&)
      (xss-lock -- xscreensaver-command --lock&)
      ;;
    lock)
      exec xscreensaver-command --lock
      ;;
  esac
fi
