#!/bin/bash
. "$HOME"/.shrc
WORKSTATION="$(workstation)"
if test -z "$WORKSTATION" || test "$HOSTNAME" = "$WORKSTATION"; then
  terminal
else
  need_auth && terminal -e ". $HOME/.shrc && auth"
  # establish a ControlMaster if possible
  ssh -n $WORKSTATION true
  terminal -e "ssh $WORKSTATION"
fi
