#!/bin/bash
. "$HOME"/.shrc
WORKSTATION="$(workstation)"
if test -z "$WORKSTATION" || test "$HOSTNAME" = "$WORKSTATION"; then
  terminal
else
  # We need to run several steps all in the same terminal.
  # - Explicitly start an interactive shell, so we can use the need_auth and
  #   auth_functions from .shrc, and can run multiple commands
  # - Run ssh -n to start an ssh ControlMaster, if possible
  # - Actually do the ssh
  terminal -e "bash -i -c 'need_auth && auth; ssh -n $WORKSTATION true; ssh $WORKSTATION'"
fi
