#!/bin/bash
# shellcheck source=/dev/null
. "$HOME"/.shrc
WORKSTATION="$(workstation)"
export WORKSTATION
if test -z "$WORKSTATION" || test "$HOSTNAME" = "$WORKSTATION"; then
  terminal
else
  terminal_on "$WORKSTATION"
fi
