#!/bin/bash
# open a file in read-only mode using the user's preferred editor

editor=${EDITOR:-vi}

case $editor in
*nano)
    readonlyflag=-v
    ;;
*vi|*vim)
    readonlyflag=-R
    ;;
esac

"$editor" $readonlyflag "$@"
